// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3001' | (string & {});
};

export type Todo = {
    _id?: string;
    title?: string;
    done?: boolean;
    createdAt?: string;
};

export type CreateTodo = {
    title: string;
};

export type GetTodosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/todos';
};

export type GetTodosResponses = {
    /**
     * List of todos
     */
    200: Array<Todo>;
};

export type GetTodosResponse = GetTodosResponses[keyof GetTodosResponses];

export type CreateTodoData = {
    body: CreateTodo;
    path?: never;
    query?: never;
    url: '/api/todos';
};

export type CreateTodoResponses = {
    /**
     * Created todo
     */
    201: Todo;
};

export type CreateTodoResponse = CreateTodoResponses[keyof CreateTodoResponses];
